site_name: Rico

theme:
  name: cinder
  site_favicon: docs/img/icon-rico.png
nav:
  - Home: index.md
  - PrÃ©-Rastrabilidade: pre_rastre.md
  - Disciplina: disciplina/disciplina.md
  - Entregas: entregas/entregas.md
  - Sprints: pontoControle/sprints.md

dev_addr: '0.0.0.0:8000'
